import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:provider/provider.dart';
import 'package:yunusco_group/helper_class/dashboard_helpers.dart';
import 'package:yunusco_group/models/qc_difference_model.dart';
import 'package:yunusco_group/providers/product_provider.dart';
import 'package:yunusco_group/screens/Products/production_dashboard.dart';
import 'package:yunusco_group/screens/Products/production_efficiency_screen.dart';
import 'package:yunusco_group/screens/Products/production_qc_screen.dart';
import 'package:yunusco_group/screens/Products/qc_difference_screen.dart';
import 'package:yunusco_group/screens/Products/widgets/production_screen.dart';
import 'package:yunusco_group/utils/colors.dart';
import 'package:yunusco_group/utils/constants.dart';

import '../../common_widgets/dashboard_item_card.dart';
import '../../models/production_qc_model.dart';
import '../../providers/riverpods/production_provider.dart';
import 'get_all_style_screen.dart';
import 'widgets/buyers_screen.dart';
import 'package:riverpod/riverpod.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

class ProductHomeScreen extends ConsumerWidget {

  @override
  Widget build(BuildContext context,WidgetRef ref) {
    final List<DashboardMenuItem> menuItems = [
      DashboardMenuItem(
        name: 'Production\nSummary',
        icon: Icons.assessment,
        cardColor: const Color(0xFFE3F2FD), // Light blue
        iconColor: const Color(0xFF1976D2), // Dark blue
        onTap: () async {
          var pp = context.read<ProductProvider>();
          await pp.getAllProductionDashboard();
          pp.getAllDhuInfo(DateTime.now());
          if (pp.productionDashboardModel != null) {
            Navigator.push(
              context,
              MaterialPageRoute(builder: (context) => ProductionDashboard()),
            );
          }
        },
      ),
      DashboardMenuItem(
        name: 'Production\nEfficiency',
        icon: Icons.assured_workload,
        cardColor: const Color(0xFFE8F5E9), // Light green
        iconColor: const Color(0xFF388E3C), // Dark green
        onTap: () async {
          var pp = context.read<ProductProvider>();
          var currentDate = convertDate(DateTime.now());
          await pp.getProductionEfficiencyReport(currentDate);
          Navigator.push(
            context,
            MaterialPageRoute(
                builder: (context) => ProductionEfficiencyScreen()),
          );
        },
      ),
      DashboardMenuItem(
        name: 'Production\nMonthly/Yearly',
        icon: Icons.calendar_month,
        cardColor: const Color(0xFFFFEBEE), // Light red
        iconColor: const Color(0xFFD32F2F), // Dark red
        onTap: () {
          Navigator.push(
            context,
            MaterialPageRoute(
                builder: (context) => const ProductionSummaryScreen()),
          );
        },
      ),
      DashboardMenuItem(
        name: 'Buyers',
        icon: Icons.people_alt_outlined,
        cardColor: const Color(0xFFF3E5F5), // Light purple
        iconColor: const Color(0xFF7B1FA2), // Dark purple
        onTap: () {
          Navigator.push(
            context,
            MaterialPageRoute(builder: (context) => BuyersScreen()),
          );
        },
      ),
      DashboardMenuItem(
        name: 'Stylewise\nEfficiency',
        icon: Icons.style_sharp,
        cardColor: const Color(0xFFFFF8E1), // Light amber
        iconColor: const Color(0xFFFFA000), // Dark amber
        onTap: () async {
          var pp = context.read<ProductProvider>();
          await pp.getAllStyleData();
          if (pp.buyerStyleList.isNotEmpty) {
            Navigator.push(
              context,
              MaterialPageRoute(builder: (context) => StyleSelectionScreen()),
            );
          }
        },
      ),
      DashboardMenuItem(
        name: 'QC\nReport',
        icon: Icons.alarm_on,
        cardColor: Colors.green, // Light amber
        iconColor: Colors.white, // Dark amber
        onTap: () async {
         final today=DashboardHelpers.convertDateTime(DateTime.now().toString(),pattern: 'yyyy-MM-dd');
          await ref.read(qcDataProvider.notifier).loadQcData(today);
          //ProductionQcListScreen(qcItems: qcItems),
         final qcDataAsync = ref.watch(qcDataProvider);
         // List<ProductionQcModel> data=[];

          // for(var i in qc_model_list){
          //   data.add(ProductionQcModel.fromJson(i));
          // }

            Navigator.push(
              context,
              MaterialPageRoute(builder: (context) => ProductionQcListScreen(qcItems: qcDataAsync,)),
            );
        },
      ),
      DashboardMenuItem(
        name: 'QC\nDifference',
        icon: Icons.difference,
        cardColor: Colors.blueAccent, // Light amber
        iconColor: Colors.white, // Dark amber
        onTap: () async {
          final today=DashboardHelpers.convertDateTime(DateTime.now().toString(),pattern: 'yyyy-MM-dd');
          await ref.read(differenceDataProvider.notifier).loadDifferenceData('date1', 'date2');
          final asyncDiffData=ref.watch(differenceDataProvider);
            Navigator.push(
              context,
              MaterialPageRoute(builder: (context) => QcDifferenceDashboard(qcDifferences: asyncDiffData,)),
            );
        },
      ),
    ];
    return Scaffold(
      backgroundColor: Colors.blue.shade50,
      appBar: AppBar(
        title: Text(
          'Production Menu',
          style: customTextStyle(18, Colors.white, FontWeight.w600),
        ),
        centerTitle: true,
        backgroundColor: myColors.primaryColor,
        iconTheme: const IconThemeData(color: Colors.white),
        systemOverlayStyle: SystemUiOverlayStyle.light,
      ),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: GridView.builder(
          gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(
            crossAxisCount: 2,
            mainAxisSpacing: 20,
            crossAxisSpacing: 20,
            childAspectRatio: 1,
          ),
          itemCount: menuItems.length,
          itemBuilder: (context, index) {
            return ReusableDashboardCard(
              menu: DashboardMenuItem(
                name: menuItems[index].name,
                icon: menuItems[index].icon,
                cardColor: menuItems[index].cardColor,
                iconColor: menuItems[index].iconColor,
                onTap: () => menuItems[index].onTap(),
              ),
            );
          },
        ),
      ),
    );
  }

  String convertDate(DateTime date) {
    // Get the individual components
    String year = date.year.toString();
    String month = date.month.toString().padLeft(2, '0');
    String day = date.day.toString().padLeft(2, '0');

    // Combine them in YYYY-MM-DD format
    return '$year-$month-$day';
  }
}


var qc_model_list =[
  {
    "SectionName": "Cutting Q.C",
    "Name": "I-11",
    "BuyerName": "PRIMARK LIMITED",
    "QmsId": 2508,
    "Date": "2025-11-13T00:00:00",
    "ProductionTimeId": 16,
    "SectionId": 20,
    "LineId": 112,
    "BuyerId": 28,
    "Style": "5PC Thong Picot Trim-1226727",
    "PO": "1226727",
    "ItemId": 7,
    "SizeId": null,
    "ColorId": null,
    "OperationId": null,
    "DefectId": null,
    "TotalPass": 3299,
    "TotalDefect": 207,
    "TotalDefectiveGarments": 179,
    "TotalReject": 0,
    "TotalAlterCheck": 178,
    "BrokenStitch": 7,
    "Pleat": 16,
    "OpenSeam": 39,
    "SkipStitch": 13,
    "Puckering": null,
    "UpDown": null,
    "Uneven": null,
    "UncutThread": 28,
    "IncorrectMeasurement": 9,
    "ColorShade": null,
    "Dirtyspot": null,
    "OilSpot": 28,
    "Wavy": 29,
    "LabelSizeMistake": null,
    "InsecureHookEyeButton": null,
    "IncompliteMissingTuck": 3,
    "Slanted": null,
    "JoinGatheringStitch": null,
    "RawEdge": null,
    "WrongPlacement": null,
    "BadTension": 4,
    "NeedleMark": null,
    "Twisting": null,
    "PoorPressing": null,
    "PressingMark": null,
    "SewingReject": null,
    "FabricReject": null,
    "OthersDefects": 31,
    "CreatedDate": "2025-11-15T16:31:10.997",
    "CreatedBy": "617",
    "UpdatedDate": null,
    "UpdatedBy": null
  },
  {
    "SectionName": "Packing Q.C",
    "Name": "J-01",
    "BuyerName": "PRIMARK LIMITED",
    "QmsId": 2509,
    "Date": "2025-11-13T00:00:00",
    "ProductionTimeId": 16,
    "SectionId": 21,
    "LineId": 113,
    "BuyerId": 28,
    "Style": "5PK MF THONG CORE-1231785",
    "PO": "1231785",
    "ItemId": 1,
    "SizeId": null,
    "ColorId": null,
    "OperationId": null,
    "DefectId": null,
    "TotalPass": 3300,
    "TotalDefect": 115,
    "TotalDefectiveGarments": 98,
    "TotalReject": 0,
    "TotalAlterCheck": 98,
    "BrokenStitch": null,
    "Pleat": 10,
    "OpenSeam": 6,
    "SkipStitch": 6,
    "Puckering": null,
    "UpDown": null,
    "Uneven": 8,
    "UncutThread": 17,
    "IncorrectMeasurement": 8,
    "ColorShade": null,
    "Dirtyspot": null,
    "OilSpot": null,
    "Wavy": 39,
    "LabelSizeMistake": 3,
    "InsecureHookEyeButton": null,
    "IncompliteMissingTuck": null,
    "Slanted": null,
    "JoinGatheringStitch": null,
    "RawEdge": null,
    "WrongPlacement": null,
    "BadTension": 1,
    "NeedleMark": null,
    "Twisting": null,
    "PoorPressing": null,
    "PressingMark": null,
    "SewingReject": null,
    "FabricReject": null,
    "OthersDefects": 15,
    "CreatedDate": "2025-11-15T16:35:41.947",
    "CreatedBy": "617",
    "UpdatedDate": null,
    "UpdatedBy": null
  },
  {
    "SectionName": "Packing Q.C",
    "Name": "J-02",
    "BuyerName": "PRIMARK LIMITED",
    "QmsId": 2510,
    "Date": "2025-11-13T00:00:00",
    "ProductionTimeId": 16,
    "SectionId": 21,
    "LineId": 114,
    "BuyerId": 28,
    "Style": "5PK MF THONG CORE-1231785",
    "PO": "1231785",
    "ItemId": 1,
    "SizeId": null,
    "ColorId": null,
    "OperationId": null,
    "DefectId": null,
    "TotalPass": 3240,
    "TotalDefect": 86,
    "TotalDefectiveGarments": 83,
    "TotalReject": 0,
    "TotalAlterCheck": 73,
    "BrokenStitch": null,
    "Pleat": 6,
    "OpenSeam": 8,
    "SkipStitch": 11,
    "Puckering": 3,
    "UpDown": null,
    "Uneven": 16,
    "UncutThread": 14,
    "IncorrectMeasurement": null,
    "ColorShade": null,
    "Dirtyspot": null,
    "OilSpot": null,
    "Wavy": 28,
    "LabelSizeMistake": null,
    "InsecureHookEyeButton": null,
    "IncompliteMissingTuck": null,
    "Slanted": null,
    "JoinGatheringStitch": null,
    "RawEdge": null,
    "WrongPlacement": null,
    "BadTension": null,
    "NeedleMark": null,
    "Twisting": null,
    "PoorPressing": null,
    "PressingMark": null,
    "SewingReject": null,
    "FabricReject": null,
    "OthersDefects": null,
    "CreatedDate": "2025-11-15T16:37:51.303",
    "CreatedBy": "617",
    "UpdatedDate": null,
    "UpdatedBy": null
  },
  {
    "SectionName": "Packing Q.C",
    "Name": "J-03",
    "BuyerName": "PRIMARK LIMITED",
    "QmsId": 2511,
    "Date": "2025-11-13T00:00:00",
    "ProductionTimeId": 16,
    "SectionId": 21,
    "LineId": 115,
    "BuyerId": 28,
    "Style": "5PK MF THONG PRINT- 1226665",
    "PO": "1226665",
    "ItemId": 1,
    "SizeId": null,
    "ColorId": null,
    "OperationId": null,
    "DefectId": null,
    "TotalPass": 2550,
    "TotalDefect": 102,
    "TotalDefectiveGarments": 91,
    "TotalReject": 0,
    "TotalAlterCheck": 89,
    "BrokenStitch": null,
    "Pleat": 8,
    "OpenSeam": null,
    "SkipStitch": 8,
    "Puckering": null,
    "UpDown": null,
    "Uneven": 15,
    "UncutThread": 4,
    "IncorrectMeasurement": 17,
    "ColorShade": null,
    "Dirtyspot": 14,
    "OilSpot": null,
    "Wavy": 19,
    "LabelSizeMistake": null,
    "InsecureHookEyeButton": null,
    "IncompliteMissingTuck": null,
    "Slanted": null,
    "JoinGatheringStitch": null,
    "RawEdge": null,
    "WrongPlacement": null,
    "BadTension": 12,
    "NeedleMark": null,
    "Twisting": null,
    "PoorPressing": null,
    "PressingMark": null,
    "SewingReject": null,
    "FabricReject": null,
    "OthersDefects": 5,
    "CreatedDate": "2025-11-15T16:40:52.157",
    "CreatedBy": "617",
    "UpdatedDate": null,
    "UpdatedBy": null
  },
  {
    "SectionName": "Packing Q.C",
    "Name": "J-04",
    "BuyerName": "PRIMARK LIMITED",
    "QmsId": 2512,
    "Date": "2025-11-13T00:00:00",
    "ProductionTimeId": 16,
    "SectionId": 21,
    "LineId": 116,
    "BuyerId": 28,
    "Style": "3PC COTTON MIAMI -1228348",
    "PO": "1228348",
    "ItemId": 1,
    "SizeId": null,
    "ColorId": null,
    "OperationId": null,
    "DefectId": null,
    "TotalPass": 400,
    "TotalDefect": 16,
    "TotalDefectiveGarments": 16,
    "TotalReject": 0,
    "TotalAlterCheck": 16,
    "BrokenStitch": null,
    "Pleat": 16,
    "OpenSeam": null,
    "SkipStitch": 23,
    "Puckering": 6,
    "UpDown": null,
    "Uneven": 27,
    "UncutThread": 33,
    "IncorrectMeasurement": null,
    "ColorShade": null,
    "Dirtyspot": null,
    "OilSpot": null,
    "Wavy": null,
    "LabelSizeMistake": null,
    "InsecureHookEyeButton": null,
    "IncompliteMissingTuck": null,
    "Slanted": null,
    "JoinGatheringStitch": null,
    "RawEdge": null,
    "WrongPlacement": null,
    "BadTension": null,
    "NeedleMark": null,
    "Twisting": null,
    "PoorPressing": null,
    "PressingMark": null,
    "SewingReject": null,
    "FabricReject": null,
    "OthersDefects": 9,
    "CreatedDate": "2025-11-15T16:43:38.493",
    "CreatedBy": "617",
    "UpdatedDate": null,
    "UpdatedBy": null
  },
  {
    "SectionName": "Packing Q.C",
    "Name": "J-05",
    "BuyerName": "PRIMARK LIMITED",
    "QmsId": 2513,
    "Date": "2025-11-13T00:00:00",
    "ProductionTimeId": 16,
    "SectionId": 21,
    "LineId": 117,
    "BuyerId": 28,
    "Style": "3PC COTTON MIAMI -1228348",
    "PO": "1228348",
    "ItemId": 1,
    "SizeId": null,
    "ColorId": null,
    "OperationId": null,
    "DefectId": null,
    "TotalPass": 2500,
    "TotalDefect": 76,
    "TotalDefectiveGarments": 49,
    "TotalReject": 0,
    "TotalAlterCheck": 49,
    "BrokenStitch": 2,
    "Pleat": 2,
    "OpenSeam": null,
    "SkipStitch": 1,
    "Puckering": 25,
    "UpDown": null,
    "Uneven": 9,
    "UncutThread": 28,
    "IncorrectMeasurement": null,
    "ColorShade": 2,
    "Dirtyspot": 4,
    "OilSpot": null,
    "Wavy": 2,
    "LabelSizeMistake": null,
    "InsecureHookEyeButton": null,
    "IncompliteMissingTuck": null,
    "Slanted": null,
    "JoinGatheringStitch": null,
    "RawEdge": null,
    "WrongPlacement": null,
    "BadTension": null,
    "NeedleMark": null,
    "Twisting": null,
    "PoorPressing": null,
    "PressingMark": null,
    "SewingReject": null,
    "FabricReject": null,
    "OthersDefects": 2,
    "CreatedDate": "2025-11-15T16:46:46.097",
    "CreatedBy": "617",
    "UpdatedDate": null,
    "UpdatedBy": null
  },
  {
    "SectionName": "Packing Q.C",
    "Name": "J-06",
    "BuyerName": "PRIMARK LIMITED",
    "QmsId": 2514,
    "Date": "2025-11-13T00:00:00",
    "ProductionTimeId": 16,
    "SectionId": 21,
    "LineId": 118,
    "BuyerId": 28,
    "Style": "5PK MF THONG PRINT- 1226665",
    "PO": "1226665",
    "ItemId": 1,
    "SizeId": null,
    "ColorId": null,
    "OperationId": null,
    "DefectId": null,
    "TotalPass": 2700,
    "TotalDefect": 70,
    "TotalDefectiveGarments": 39,
    "TotalReject": 0,
    "TotalAlterCheck": 39,
    "BrokenStitch": 1,
    "Pleat": 3,
    "OpenSeam": null,
    "SkipStitch": 7,
    "Puckering": null,
    "UpDown": null,
    "Uneven": null,
    "UncutThread": 13,
    "IncorrectMeasurement": 18,
    "ColorShade": null,
    "Dirtyspot": null,
    "OilSpot": null,
    "Wavy": 17,
    "LabelSizeMistake": 1,
    "InsecureHookEyeButton": null,
    "IncompliteMissingTuck": null,
    "Slanted": null,
    "JoinGatheringStitch": null,
    "RawEdge": null,
    "WrongPlacement": null,
    "BadTension": null,
    "NeedleMark": null,
    "Twisting": null,
    "PoorPressing": null,
    "PressingMark": null,
    "SewingReject": null,
    "FabricReject": null,
    "OthersDefects": 10,
    "CreatedDate": "2025-11-15T16:49:07.433",
    "CreatedBy": "617",
    "UpdatedDate": null,
    "UpdatedBy": null
  },
  {
    "SectionName": "Packing Q.C",
    "Name": "J-07",
    "BuyerName": "PRIMARK LIMITED",
    "QmsId": 2515,
    "Date": "2025-11-13T00:00:00",
    "ProductionTimeId": 16,
    "SectionId": 21,
    "LineId": 119,
    "BuyerId": 28,
    "Style": "3PC COTTON MIAMI -1228348",
    "PO": "1228348",
    "ItemId": 1,
    "SizeId": null,
    "ColorId": null,
    "OperationId": null,
    "DefectId": null,
    "TotalPass": 1400,
    "TotalDefect": 69,
    "TotalDefectiveGarments": 84,
    "TotalReject": 0,
    "TotalAlterCheck": 84,
    "BrokenStitch": 9,
    "Pleat": 9,
    "OpenSeam": 10,
    "SkipStitch": 6,
    "Puckering": 16,
    "UpDown": null,
    "Uneven": 11,
    "UncutThread": 15,
    "IncorrectMeasurement": null,
    "ColorShade": null,
    "Dirtyspot": null,
    "OilSpot": null,
    "Wavy": 20,
    "LabelSizeMistake": null,
    "InsecureHookEyeButton": null,
    "IncompliteMissingTuck": null,
    "Slanted": null,
    "JoinGatheringStitch": null,
    "RawEdge": null,
    "WrongPlacement": null,
    "BadTension": null,
    "NeedleMark": null,
    "Twisting": null,
    "PoorPressing": null,
    "PressingMark": null,
    "SewingReject": null,
    "FabricReject": null,
    "OthersDefects": null,
    "CreatedDate": "2025-11-15T16:51:10.467",
    "CreatedBy": "617",
    "UpdatedDate": null,
    "UpdatedBy": null
  },
  {
    "SectionName": "Packing Q.C",
    "Name": "J-08",
    "BuyerName": "PRIMARK LIMITED",
    "QmsId": 2516,
    "Date": "2025-11-13T00:00:00",
    "ProductionTimeId": 16,
    "SectionId": 21,
    "LineId": 120,
    "BuyerId": 28,
    "Style": "3PC COTTON MIAMI -1228348",
    "PO": "1228348",
    "ItemId": 1,
    "SizeId": null,
    "ColorId": null,
    "OperationId": null,
    "DefectId": null,
    "TotalPass": 1999,
    "TotalDefect": 80,
    "TotalDefectiveGarments": 79,
    "TotalReject": 0,
    "TotalAlterCheck": 79,
    "BrokenStitch": 22,
    "Pleat": 5,
    "OpenSeam": 6,
    "SkipStitch": 10,
    "Puckering": 2,
    "UpDown": null,
    "Uneven": 1,
    "UncutThread": 20,
    "IncorrectMeasurement": null,
    "ColorShade": null,
    "Dirtyspot": 17,
    "OilSpot": null,
    "Wavy": 5,
    "LabelSizeMistake": null,
    "InsecureHookEyeButton": null,
    "IncompliteMissingTuck": null,
    "Slanted": null,
    "JoinGatheringStitch": null,
    "RawEdge": null,
    "WrongPlacement": null,
    "BadTension": null,
    "NeedleMark": null,
    "Twisting": null,
    "PoorPressing": null,
    "PressingMark": null,
    "SewingReject": null,
    "FabricReject": null,
    "OthersDefects": 2,
    "CreatedDate": "2025-11-15T16:53:43.777",
    "CreatedBy": "617",
    "UpdatedDate": null,
    "UpdatedBy": null
  },
  {
    "SectionName": "Packing Q.C",
    "Name": "J-09",
    "BuyerName": "PRIMARK LIMITED",
    "QmsId": 2517,
    "Date": "2025-11-13T00:00:00",
    "ProductionTimeId": 16,
    "SectionId": 21,
    "LineId": 121,
    "BuyerId": 28,
    "Style": "4PK MF FULL BRIEF CORE- 1231655",
    "PO": "1231655",
    "ItemId": 1,
    "SizeId": null,
    "ColorId": null,
    "OperationId": null,
    "DefectId": null,
    "TotalPass": 2400,
    "TotalDefect": 66,
    "TotalDefectiveGarments": 58,
    "TotalReject": 0,
    "TotalAlterCheck": 58,
    "BrokenStitch": null,
    "Pleat": 4,
    "OpenSeam": 14,
    "SkipStitch": null,
    "Puckering": null,
    "UpDown": null,
    "Uneven": 19,
    "UncutThread": 8,
    "IncorrectMeasurement": null,
    "ColorShade": null,
    "Dirtyspot": null,
    "OilSpot": null,
    "Wavy": 15,
    "LabelSizeMistake": null,
    "InsecureHookEyeButton": null,
    "IncompliteMissingTuck": 6,
    "Slanted": null,
    "JoinGatheringStitch": null,
    "RawEdge": null,
    "WrongPlacement": null,
    "BadTension": null,
    "NeedleMark": null,
    "Twisting": null,
    "PoorPressing": null,
    "PressingMark": null,
    "SewingReject": null,
    "FabricReject": null,
    "OthersDefects": null,
    "CreatedDate": "2025-11-15T16:55:37.697",
    "CreatedBy": "617",
    "UpdatedDate": null,
    "UpdatedBy": null
  },
  {
    "SectionName": "Packing Q.C",
    "Name": "J-10",
    "BuyerName": "PRIMARK LIMITED",
    "QmsId": 2518,
    "Date": "2025-11-13T00:00:00",
    "ProductionTimeId": 16,
    "SectionId": 21,
    "LineId": 122,
    "BuyerId": 28,
    "Style": "4PK MF FULL BRIEF CORE- 1231655",
    "PO": "1231655",
    "ItemId": 1,
    "SizeId": null,
    "ColorId": null,
    "OperationId": null,
    "DefectId": null,
    "TotalPass": 3300,
    "TotalDefect": 110,
    "TotalDefectiveGarments": 90,
    "TotalReject": 0,
    "TotalAlterCheck": 90,
    "BrokenStitch": 13,
    "Pleat": 8,
    "OpenSeam": 7,
    "SkipStitch": 2,
    "Puckering": 2,
    "UpDown": null,
    "Uneven": 26,
    "UncutThread": 16,
    "IncorrectMeasurement": 7,
    "ColorShade": null,
    "Dirtyspot": 2,
    "OilSpot": null,
    "Wavy": 13,
    "LabelSizeMistake": null,
    "InsecureHookEyeButton": null,
    "IncompliteMissingTuck": null,
    "Slanted": null,
    "JoinGatheringStitch": null,
    "RawEdge": null,
    "WrongPlacement": null,
    "BadTension": null,
    "NeedleMark": null,
    "Twisting": null,
    "PoorPressing": null,
    "PressingMark": null,
    "SewingReject": null,
    "FabricReject": null,
    "OthersDefects": 4,
    "CreatedDate": "2025-11-15T16:57:41.597",
    "CreatedBy": "617",
    "UpdatedDate": null,
    "UpdatedBy": null
  }
];


var qc_difference=[
  {
    "LineName": "F-06",
    "SectionName": "Sewing",
    "BuyerName": "La-Halle",
    "TotalPass_Date1": 1733,
    "TotalDefect_Date1": 67,
    "TotalReject_Date1": 0,
    "TotalPass_Date2": 1930,
    "TotalDefect_Date2": 70,
    "TotalReject_Date2": 0,
    "Pass_Difference": 197,
    "Defect_Difference": 3,
    "Reject_Difference": 0
  },
  {
    "LineName": "F-07",
    "SectionName": "Sewing",
    "BuyerName": "PRIMARK LIMITED",
    "TotalPass_Date1": 1900,
    "TotalDefect_Date1": 131,
    "TotalReject_Date1": 0,
    "TotalPass_Date2": 1900,
    "TotalDefect_Date2": 119,
    "TotalReject_Date2": 0,
    "Pass_Difference": 0,
    "Defect_Difference": -12,
    "Reject_Difference": 0
  },
  {
    "LineName": "F-08",
    "SectionName": "Sewing",
    "BuyerName": "KIABI",
    "TotalPass_Date1": 2130,
    "TotalDefect_Date1": 206,
    "TotalReject_Date1": 0,
    "TotalPass_Date2": 1000,
    "TotalDefect_Date2": 127,
    "TotalReject_Date2": 0,
    "Pass_Difference": -1130,
    "Defect_Difference": -79,
    "Reject_Difference": 0
  },
  {
    "LineName": "F-09",
    "SectionName": "Sewing",
    "BuyerName": "PRIMARK LIMITED",
    "TotalPass_Date1": 2700,
    "TotalDefect_Date1": 117,
    "TotalReject_Date1": 0,
    "TotalPass_Date2": 2600,
    "TotalDefect_Date2": 134,
    "TotalReject_Date2": 0,
    "Pass_Difference": -100,
    "Defect_Difference": 17,
    "Reject_Difference": 0
  },
  {
    "LineName": "F-10",
    "SectionName": "Sewing",
    "BuyerName": "VERTBAUDET SAS",
    "TotalPass_Date1": 2700,
    "TotalDefect_Date1": 148,
    "TotalReject_Date1": 0,
    "TotalPass_Date2": 1500,
    "TotalDefect_Date2": 95,
    "TotalReject_Date2": 0,
    "Pass_Difference": -1200,
    "Defect_Difference": -53,
    "Reject_Difference": 0
  },
  {
    "LineName": "F-11",
    "SectionName": "Sewing",
    "BuyerName": "PRIMARK LIMITED",
    "TotalPass_Date1": 2085,
    "TotalDefect_Date1": 144,
    "TotalReject_Date1": 0,
    "TotalPass_Date2": 2175,
    "TotalDefect_Date2": 166,
    "TotalReject_Date2": 0,
    "Pass_Difference": 90,
    "Defect_Difference": 22,
    "Reject_Difference": 0
  },
  {
    "LineName": "G-01",
    "SectionName": "Molding",
    "BuyerName": "KIABI",
    "TotalPass_Date1": 1450,
    "TotalDefect_Date1": 152,
    "TotalReject_Date1": 0,
    "TotalPass_Date2": 1450,
    "TotalDefect_Date2": 148,
    "TotalReject_Date2": 0,
    "Pass_Difference": 0,
    "Defect_Difference": -4,
    "Reject_Difference": 0
  },
  {
    "LineName": "G-04",
    "SectionName": "Molding",
    "BuyerName": "KIABI",
    "TotalPass_Date1": 2400,
    "TotalDefect_Date1": 193,
    "TotalReject_Date1": 0,
    "TotalPass_Date2": 2300,
    "TotalDefect_Date2": 175,
    "TotalReject_Date2": 0,
    "Pass_Difference": -100,
    "Defect_Difference": -18,
    "Reject_Difference": 0
  }
];
